"""
Django settings for VibePassApp project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import cloudinary
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY=os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =os.getenv('DEBUG')

ALLOWED_HOSTS =os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost,0.0.0.0,.ngrok-free.dev,.ngrok-free.app').split(',')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    'Users',
    'Events',
    'Tickets',
    'Payments',
    'Pages',

    'cloudinary_storage',
    'cloudinary',
    'django_ngrok',
    'channels',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'axes',

    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'two_factor',
    'two_factor.plugins.phonenumber',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'VibePassApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'VibePassApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv('DATABASE_ENGINE'),
        "NAME": os.getenv('DATABASE_NAME'),
        "USER": os.getenv('DATABASE_USER'),
        "PASSWORD": os.getenv('DATABASE_PASSWORD'),
        "HOST": os.getenv('DATABASE_HOST'),
        "PORT": os.getenv('DATABASE_PORT'),
    }
}


# specify custom user model
AUTH_USER_MODEL = 'Users.User'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'
MEDIA_URL = '/media/'  # or any prefix you choose


STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
    api_key=os.getenv('CLOUDINARY_API_KEY'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET')
)

# Channels configuration
ASGI_APPLICATION = 'VibePassApp.asgi.application'

# Channel layers for WebSockets
# VibePassApp/settings.py
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # Use explicit connection kwargs so redis-py / aioredis get sensible timeouts
            # and health checking to avoid spurious TimeoutError exceptions.
            "hosts": [
                {
                    "host": "redis",
                    "port": 6379,
                    # Seconds to wait for a socket read before raising TimeoutError
                    "socket_timeout": 60,
                    # Seconds to wait for socket connect
                    "socket_connect_timeout": 10,
                    # Periodically check connections to ensure liveness
                    "health_check_interval": 10,
                }
            ],
            "capacity": 1500,
            "expiry": 10,
        },
    },
}

AUTHENTICATION_BACKENDS = (
    # Axes backend for handling login attempts and lockouts
    'axes.backends.AxesStandaloneBackend',

    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",

    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
)


SOCIALACCOUNT_PROVIDERS = \
    { 'google':
        { 
          'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET'),
            'key': ''
          },
          'SCOPE': ['profile', 'email'],
          'AUTH_PARAMS': { 'access_type': 'online' },
          'METHOD': 'oauth2',
        }
    }

SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True

ACCOUNT_SIGNUP_METHODS = {'email*', 'username'}
ACCOUNT_UNIQUE_EMAIL = True

SITE_ID = 1

CSRF_TRUSTED_ORIGINS = [
    'https://gawk-quack-uniformed.ngrok-free.dev',
]

# Django Axes configuration settings
AXES_FAILURE_LIMIT = 3   # attempts user can try

AXES_COOLOFF_TIME = timedelta(minutes=15)  # how long before reset

AXES_LOCKOUT_PARAMETERS = [
    ["username", "ip_address", "user_agent"],  # Locks device based on this
]

AXES_RESET_ON_SUCCESS = True # Resets the failed login attempts after a successful login

AXES_VERBOSE = True # Enables verbose logging for Axes, providing detailed information about lockouts and failed login attempts



# Django-OTP and Two-Factor Authentication settings
TWO_FACTOR_PATCH_ADMIN = False  #Intercepts the admin login view and adds 2FA to it

LOGIN_URL = 'two_factor:login' #Redirects the user to the 2FA login view instead of the default login view

LOGIN_REDIRECT_URL = 'finders_dashboard' #Redirects the user to the admin dashboard after successful login

LOGOUT_REDIRECT_URL = '/' #Redirects the user to the home page after admin logout

TWO_FACTOR_TOTP_DIGITS = 6 #N.O of TOTP digits

TWO_FACTOR_LOGIN_TIMEOUT = 200 #Time in seconds before the 2FA login session expires

if 'test' in sys.argv:
    AXES_ENABLED = False  # Disable Axes during testing to avoid lockouts

CELERY_BROKER_URL=os.getenv('CELERY_BROKER_URL') # Celery Broker URL
CELERY_RESULT_BACKEND=os.getenv('CELERY_BROKER_URL')
