# Generated by Django 6.0.1 on 2026-04-10 10:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_ticket_status_ticket_user_alter_ticket_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_qr_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ticket_qr_image'),
        ),
    ]
