# Generated by Django 6.0.1 on 2026-06-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_remove_event_event_ticket_price_and_more'),
        ('Tickets', '0003_ticket_ticket_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Events.tickettype'),
        ),
    ]
