# Generated by Django 6.0.1 on 2026-09-25 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0019_alter_event_event_organiser_alter_tickettype_event"),
        (
            "Payments",
            "0011_alter_escrowmodel_event_alter_escrowmodel_organiser_and_more",
        ),
        ("Tickets", "0005_alter_ticket_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ticket",
                to="Payments.payment",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="Events.tickettype",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booked_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
