# Generated by Django 6.0.1 on 2026-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tickets", "0006_alter_ticket_payment_alter_ticket_ticket_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("scanned", "Scanned"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
