# Generated by Django 6.0.1 on 2026-10-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tickets", "0007_alter_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
