# Generated by Django 6.0.1 on 2026-04-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_alter_payment_mpesa_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
