# Generated by Django 6.0.1 on 2026-05-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_withdrawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='organizer',
            new_name='organiser',
        ),
    ]
