# Generated by Django 6.0.1 on 2026-06-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0005_rename_organizer_withdrawal_organiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
