# Generated by Django 6.0.1 on 2026-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_payment_is_agreed_to_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_data_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
