# Generated by Django 6.0.1 on 2026-09-25 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0019_alter_event_event_organiser_alter_tickettype_event"),
        ("Payments", "0010_escrowmodel_release_dates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="escrowmodel",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="Events.event",
            ),
        ),
        migrations.AlterField(
            model_name="escrowmodel",
            name="organiser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organisers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="escrowmodel",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="Payments.payment",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="Events.event",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="organiser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withdrawals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PlatformRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("source", models.CharField(default="Early-Payout", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organiser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
