# Generated by Django 6.0.1 on 2026-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Payments",
            "0011_alter_escrowmodel_event_alter_escrowmodel_organiser_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="escrowmodel",
            name="payout_status",
            field=models.CharField(
                choices=[
                    ("held", "Held"),
                    ("frozen", "Frozen"),
                    ("refunded", "Refunded"),
                    ("released", "Released"),
                ],
                default="held",
                max_length=20,
            ),
        ),
    ]
