# Generated by Django 6.0.1 on 2026-10-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payments", "0012_alter_escrowmodel_payout_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdrawal",
            name="mpesa_receipt_number",
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="status_conversation_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
