# Generated by Django 6.0.1 on 2026-02-01 12:07

import Events.models
import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_title', models.CharField(max_length=200)),
                ('Event_flyer', cloudinary.models.CloudinaryField(max_length=255, validators=[Events.models.validate_image_size], verbose_name='image')),
                ('Event_details', models.TextField()),
                ('Event_location', models.CharField(max_length=200)),
                ('Event_date', models.DateField()),
                ('Event_time', models.TimeField()),
                ('Event_mpesa_number', models.CharField(max_length=15)),
                ('Event_ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Event_is_free', models.BooleanField(default=False)),
                ('Event_total_tickets', models.PositiveIntegerField()),
                ('Event_is_active', models.BooleanField(default=True)),
                ('Event_created_at', models.DateTimeField(auto_now_add=True)),
                ('Event_organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
