# Generated by Django 6.0.1 on 2026-02-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Event_category',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
