# Generated by Django 6.0.1 on 2026-02-09 19:22

import Events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_event_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_flyer',
            field=models.ImageField(upload_to='images/', validators=[Events.models.validate_image_size]),
        ),
    ]
