# Generated by Django 6.0.1 on 2026-02-09 20:00

import Events.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_event_event_flyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_flyer',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[Events.models.validate_image_size], verbose_name='image'),
        ),
    ]
