# Generated by Django 6.0.1 on 2026-02-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_alter_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
