# Generated by Django 6.0.1 on 2026-02-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_remove_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
