# Generated by Django 6.0.1 on 2026-04-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0010_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_mpesa_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
