# Generated by Django 6.0.1 on 2026-06-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0011_alter_event_event_mpesa_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_category',
            field=models.CharField(choices=[('live music', 'Live Music'), ('sports', 'Sports'), ('workshop', 'Workshop'), ('campus parties', 'Campus Parties'), ('tech events', 'Tech Events'), ('networking', 'Networking'), ('festivals', 'Festivals'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
