# Generated by Django 6.0.1 on 2026-06-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0012_alter_event_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Event_ticket_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Event_total_tickets',
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='Events.event')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('event', 'name')},
            },
        ),
    ]
