# Generated by Django 6.0.1 on 2026-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_remove_event_event_ticket_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
