# Generated by Django 6.0.1 on 2026-08-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0015_eventscanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='group_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
