# Generated by Django 6.0.1 on 2026-09-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0017_event_event_is_flagged_event_event_payout_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="Event_mpesa_number",
        ),
        migrations.RemoveField(
            model_name="event",
            name="Event_payout_status",
        ),
        migrations.AlterField(
            model_name="reportevent",
            name="report_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under_Review"),
                    ("action_taken", "Action_Taken"),
                    ("dismissed", "Dismissed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
