# Generated by Django 6.0.1 on 2026-09-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0019_alter_event_event_organiser_alter_tickettype_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="Event_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("deleted", "Deleted"),
                ],
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
