# Generated by Django 6.0.1 on 2026-09-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0020_event_event_status_event_cancel_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="cancel_reason",
        ),
        migrations.AlterField(
            model_name="event",
            name="Event_status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("deleted", "Deleted"),
                ],
                default="published",
                max_length=20,
            ),
        ),
    ]
