# Generated by Django 6.0.1 on 2026-09-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_user_account_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
    ]
