# Generated by Django 6.0.1 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0005_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mpesa_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
