# Generated by Django 6.0.1 on 2026-09-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0005_user_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
