# Generated by Django 6.0.1 on 2026-09-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_user_mpesa_number"),
        ("Users", "0007_organizerprofile"),
    ]

    operations = []
