# Generated by Django 6.0.1 on 2026-09-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0009_organizerwallet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="account_balance",
        ),
    ]
