# Generated by Django 6.0.1 on 2026-09-25 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0010_remove_user_account_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organizer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organizerwallet",
            name="organiser",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organiser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
